# general configuration
url: http://http://anbasile.github.io/
baseurl: ''
site_name: 'Angelo Basile personal home page'

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Angelo Basile"
  # tagline will appear under the title (optional)
  tagline: "M.A. in Philosophy, Logics & Informatics / University of Trento"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  
##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True   # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10      # Default 10
start-delay: 200    # Default 200
delete-delay: 5000  # Default 5000
lines:          # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
