# general configuration
url: 'http://anbasile.github.io'
baseurl: ''
email: 'angelobasile@yandex.ru'
# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/img/logo.svg"
  # author will appear under the avatar (optional)
  author: "Angelo Basile"
  # tagline will appear under the title (optional)
  tagline: "MSc in Philosophy/ <br /> University of Trento"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Permalinks
permalink: pretty

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-time-to-read
